//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lws.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class State
    {
        public int Id { get; set; }
        public string SensorSsn { get; set; }
        public Nullable<System.DateTime> LastTimeUpdate { get; set; }
        public Nullable<System.DateTime> NextTimeUpdate { get; set; }
        public Nullable<decimal> VoltLevel { get; set; }
        public Nullable<decimal> CurrentBill { get; set; }
        public Nullable<int> Error { get; set; }
    
        public virtual Sensor Sensor { get; set; }
    }
}
