//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lws.Domain
{
    using System;
    using System.ComponentModel;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class Value
    {
        public int Id { get; set; }

        [DisplayName("Server time")]
        [DataMember(Name = "serverTime")]
        public System.DateTime ServerDate { get; set; }

        [DisplayName("Device time")]
        [DataMember(Name = "deviceTime")]
        public Nullable<System.DateTime> SensorDate { get; set; }

        [DisplayName("Negative pulses")]
        [DataMember(Name = "negativePulses")]
        public Nullable<int> NumberOfNP { get; set; }

        [DisplayName("Positive pulses")]
        [DataMember(Name = "positivePulses")]
        public Nullable<int> NumberOfPP { get; set; }

        [DisplayName("Temperature")]
        [DataMember(Name = "temperature")]
        public Nullable<int> Meter1Value { get; set; }

        [DisplayName("Wind")]
        [DataMember(Name = "wind")]
        public Nullable<int> Meter2Value { get; set; }

        [DisplayName("E-Field")]
        [DataMember(Name = "eField")]
        public Nullable<int> Meter3Value { get; set; }

        [DisplayName("Id")]
        [DataMember(Name = "ssn")]
        public string SensorSsn { get; set; }

        public virtual Sensor Sensor { get; set; }
    }
}
